### ISSUE TITLE
Request on update with channel getting error

### ISSUE THREAD

**Issue by Samuell1** [aluxian/squirrel-updates-server#18]
Hey, i switch from normal update `update/win32` to using channels but if its going to find update there is error and its doing 2 request.

Any idea how to fix this?

First request its OK
```
/update/stable/win32/RELEASES?id=app&localVersion=0.0.58&arch=amd64
```

Next request is ERROR, because relases is lowercase
```
/update/stable/win32/releases?id=app&localversion=0.0.58&arch=amd64
```

**Comment by aluxian** [comment]
You could copy "RELEASES" to "releases" and upload both to the Github release. That should fix it, but it's treating the symptom not the cause. I don't have time to look into this, sorry.

**Comment by Samuell1** [comment]
@aluxian thanks for response! I think there is some bug in channel handling or something because normal `/update/win32` is working fine without 2 requests.

**Comment by Samuell1** [comment]
@aluxian i found out its same without channel too :/ I switched from docker to normal server, can be issue with it?

**Comment by wlindley** [comment]
I'm also experiencing this. This is the error I'm getting:
`2017-08-08 09:23:09> IEnableLogger: Failed to download url: http://my.url.com/update/stable/win32/RELEASES?id=MyApp&localVersion=2017.12.0&arch=amd64: System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38'1.MoveNext()`

I think the lowercase releases is the client retrying with a different URL to see if it will work. If the all caps RELEASES URL succeeds, I doubt it will try the lowercase one. What's also weird is that the same URL works fine in a Chrome browser and successfully downloads the RELEASES files. My theory is that there's something about the way it redirects that's problematic, but I'm not sure what.
